baseURL = 'https://aerrasagas.github.io'
languageCode = 'fr-fr'
title = 'AÃ«rra Sagas'
theme = "PaperMod"

[taxonomies]
tag = "tags"


[params]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"